### ISSUE TITLE
health final tracking

### ISSUE THREAD

**Issue by DinkyInkyDog** [DinkyInkyDog/dndtracker#5]
There's only a few more things I want to add to the health part of this tracker. the full health button, the instant death button, and the progress bar for the current health. OH! and the max health label above that progress bar.

### goals

- [ ] implement full health button
- [ ] implement instant death button
- [ ] #6
- [ ] add max health display

**Comment by DinkyInkyDog** [comment]
![Image](https://github.com/user-attachments/assets/4c5b9f02-805e-4a5c-aee8-7816f89e0188)


I think I like the placement of each of the new functions. First thing on my list is to make the assets. Then I'm going to do some research into making the task bar work.
